### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ijl** [nsqio/pynsq#107]
Is Python 3 support a goal? Would a patch be accepted?

**Comment by mreiferson** [comment]
@ilj what else is needed for python 3.0 compatibility?  can we close this?

**Comment by ijl** [comment]
@mreiferson I'll open one more PR on this soon.

**Comment by pennomi** [comment]
Is this happening? I keep hearing good things about NSQ, but no Python 3 support is a deal breaker for me.

**Comment by mreiferson** [comment]
@pennomi it's not clear to me what's still needed for this

**Comment by pennomi** [comment]
I don't know if I can commit to porting it myself, but here's the general strategy:

 * Make sure your unit tests are up to date and have good coverage. Port those first!
 * Don't bother with `2to3`. It works okay for one-way porting, but your goal should be a codebase that runs in a version-agnostic way.
 * Use as many `__future__` imports in every file as you can
 * Use modern syntax wherever possible. Good Python 2.7 code looks almost identical to Python 3.
 * Use the dependency `six` to bridge the remaining gaps in your code. (This will fix changed imports as well as any other syntactic differences).
 * When you're done, you should have one codebase that runs on both Python 2 and 3. Maintaining this should be easy once the initial work is done.

See also [the Django Project](https://docs.djangoproject.com/en/1.8/topics/python3/) for notes on how they did their porting.

**Comment by mreiferson** [comment]
@pennomi - #127 was opened by @ijl to address this issue

**Comment by nickstenning** [comment]
I'm also keen to see a release of pynsq that supports Python 3. I'm currently looking at improving on #127, which is great as far as it goes, but it provides little context as to the changes that are being made, introduces new behaviour for encoding of data to be sent to the server, and doesn't appear to be passing the test suites.

With any luck https://travis-ci.org/nickstenning/pynsq/builds/109237372 will go green, but I want to be clear that I haven't *actually* tested the resulting build of pynsq, merely run the tests!

At the moment I'm targeting only Python 3.5 -- earlier versions are a bit of a PITA, due to the lack of various features (e.g. %-interpolation for bytestrings) that were introduced in 3.5.

**Comment by santagada** [comment]
I think the .travis should be adjusted to run only go 1.4.3, latest 1.5 and latest 1.6 (not 1.3 like it is right now) and test only on python 2.7 and 3.4+ (no need for python 2.6 anymore). also tornado is at version 4.3 now.

**Comment by qhgongzi** [comment]
we need this feature, our production environment is python3.

**Comment by mreiferson** [comment]
done in #150
