### ISSUE TITLE
reader: option for reconnection when losing connection

### ISSUE THREAD

**Issue by Jannik-Lappe** [nsqio/pynsq#193]
Is there a plan for an option to reconnect on connection lost? Or at least a feedback whether or not the reader has established a connection?
I'm running the reader in a own process.
Until now I couldn't find a way to get a sign if the reader lost his connection.

**Comment by ploxiln** [comment]
pynsq does reconnect and it does emit log messages about it. What you might be experiencing is the case where pynsq has no good way of knowing that the connection was lost, because there was no FIN or RST packet (this is possible if a firewall/NAT is being annoying or if the remote end abruptly lost connection for example by being unplugged).

There is a "tcp keepalive" feature that can probably be enabled/configured for your OS. nsq does not currently have an application-level keep-alive feature, like ssh and websockets do. (These features use a active method to ensure the remote end of the connection is still responsive.)
