### ISSUE TITLE
Any plan to release a new version which support tornado 5.x?

### ISSUE THREAD

**Issue by shuoli84** [nsqio/pynsq#239]

**Comment by ploxiln** [comment]
you can install the pre-release 0.9.0b1 explicitly using pip:

```
pip install pynsq==0.9.0b1
```

**Comment by shuoli84** [comment]
@ploxiln sure, any reason why it stays in beta? I run this code in production, so...

**Comment by katzdm** [comment]
Wanted to bump this - Are there any known issues blocking the promotion of `0.9.0b1` to a full release?

**Comment by katzdm** [comment]
Also note that version `0.9.0b1` remains incompatible with `tornado>=6.0` (this is likely known, but I want to state it here explicitly, for the benefit of others).

The particular incompatibility that I encountered was the removal of the `callback`-parameter from Tornado's `httpclient.fetch()` function. This leaves `callback` to be included in `kwargs`, which causes an exception to be thrown, since Tornado disallows `kwargs` to be passed in conjunction with an `HTTPRequest`.

**Comment by ploxiln** [comment]
the tornado requirement would ideally be checked by your install system somehow:
https://github.com/nsqio/pynsq/blob/v0.9.0b1/setup.py#L35

tornado-6.0 support is on my mind, I may tackle it someday soon :)

**Comment by ploxiln** [comment]
@jehiah @mreiferson I've been using pynsq-0.9.0b1 with tornado-5.1.1 on python-3.6.z for a while, seems to work :)

It's probably a good idea to make a "stable" release of 0.9.0 sometime before tornado-6 support may be merged.

**Comment by mreiferson** [comment]
see #244
